image: continuumio/miniconda3:latest

before_script:
  - apt-get update -qq && apt-get install -q --yes pylint
  - conda env create --file environment.yml --quiet
  - source activate mqtl


tests:
  stage: test
  script:
    - pylint --output-format=text *.py || exit 0
#    - for f in *.py; do echo "${f}"; python3 "${f}" --version; done
